schema_version = "1.0.0"

id = "quickpath_rknz"
version = "2.0.0"
name = "QuickPath RKNZ"
tagline = "Quick motion path visualization for bones and objects"
maintainer = "Rikokenz <https://rikokensfw.carrd.co>"
type = "add-on"
website = "https://rikokensfw.carrd.co"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
